CREATE USER 'fel'@'localhost' IDENTIFIED BY 'fel' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

CREATE DATABASE `fel_auth` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `fel_characters` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE `fel_world` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `fel_auth` . * TO 'fel'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `fel_characters` . * TO 'fel'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `fel_world` . * TO 'fel'@'localhost' WITH GRANT OPTION;
